### ISSUE TITLE
Talk Feature

### ISSUE THREAD

**Issue by hectoritr** [cboard-org/fluid-mind#4]
### Talk Feature
This feature is to start a conversation by creating a sentence. The model will take into consideration the chat history if present, the user bio if present, keywords if present and the tone. 
How to respond is meant to be the user intent, for now we will show only 4 options, but can be more (like a Cboard board) to offer the user many possible intents. 

```
const requestBody = {
    chat_history: [],
    how_to_respond: "See below",
    keywords: "comma,separated,keywords",
    sentence: " ", //Send an empty sentence if it is the first, send the last sentence if the user selects a sentence from the chat history.
    tone: "funny",
    user_pref:
      "Hector a Biomedical engineer who lives in Carlos Paz. Recently you had one 11-month old little girl. You like sail boats and F1 ",
  };
```

Here’s how the user intent should be displayed and sent to the model for processing:
Display: **Make a Statement**
Send to the model:  "to present factual information or make a clear statement."

Display: **Ask a Question**
Send to the model: "to inquire or ask questions for more information."

Display: **Social Interaction**
Send to the model: "to engage in friendly conversation or casual social interaction."

Display: **Make Plans**
Send to the model: "to suggest or organize future plans or activities."

Here’s a list of possible intents that would fit the structure of the sentence:

Inform: Sharing factual or descriptive information.
Instruct: Giving directions or steps to follow.
Persuade: Convincing someone to adopt a viewpoint or take action.
Inquire: Asking for information or clarification.
Express: Conveying emotions or thoughts.
Propose: Suggesting an idea or course of action.
Advise: Offering guidance or recommendations.
Clarify: Ensuring understanding or providing more detail.
Apologize: Expressing regret for an action.
Compliment: Offering praise or appreciation.
Warn: Alerting someone to a danger or risk.
Negotiate: Finding common ground or reaching a compromise.

**Comment by tomivm** [comment]
The first version was included on [this commit](https://github.com/cboard-org/fluid-mind/commit/46d42e4f66465f1c6d464f17635bddfa18af17aa)
I add a new issue to continue with the development and design of this feature. See #7
